application:
  yandex-key: ${YANDEX_API_TOKEN:}
  ytdlLocation: ${YTDL_LOCATION:}
  openAiToken: ${OPEN_AI_TOKEN:}
  bot-name-aliases: ${BOT_NAME_ALIASES:}

telegram:
  bot-name: ${BOT_NAME:}
  bot-token: ${BOT_TOKEN:}
  developer: ${BOT_OWNER_NAME:}
  developer-id: ${BOT_OWNER_TELEGRAM_ID:}
  payment-token: ${PAYMENT_TOKEN:}

spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/family}
    driver-class-name: "org.postgresql.Driver"
    username: ${POSTGRES_USER:family}
    password: ${POSTGRES_PASSWORD:family}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
management:
  metrics:
    enable:
      all: false
  graphite:
    metrics:
      export:
        enabled: false
